// <auto-generated />
using Lemmikkitietokanta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LemmikkitietokantaSovellus.Migrations
{
    [DbContext(typeof(LemmikkiDbContext))]
    [Migration("20241101182128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Lemmikkitietokanta.Models.Lemmikki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OmistajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rotu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OmistajaId");

                    b.ToTable("Lemmikit", (string)null);
                });

            modelBuilder.Entity("Lemmikkitietokanta.Models.Omistaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Puhelin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Omistajat", (string)null);
                });

            modelBuilder.Entity("Lemmikkitietokanta.Models.Lemmikki", b =>
                {
                    b.HasOne("Lemmikkitietokanta.Models.Omistaja", "Omistaja")
                        .WithMany("Lemmikit")
                        .HasForeignKey("OmistajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Omistaja");
                });

            modelBuilder.Entity("Lemmikkitietokanta.Models.Omistaja", b =>
                {
                    b.Navigation("Lemmikit");
                });
#pragma warning restore 612, 618
        }
    }
}
